### ISSUE TITLE
It's not shaking in Chrome 

### ISSUE THREAD

**Issue by mlotfi2005** [elrumordelaluz/csshake#13]
Hi,
I just downloaded your csshake.min.css, it's working fine in Internet Explorer and FireFox, but it's not working in Chrome, any finx for this will be appreciated.
Thanks

**Comment by blainesch** [comment]
Working for me in Chrome 45.0.2454.99 (64-bit)

**Comment by elrumordelaluz** [comment]
@blainesch I think it was an old issue related on prefixes that today Chrome doesn't need anymore.
