### ISSUE TITLE
Shake child element instead of entire parent

### ISSUE THREAD

**Issue by mouse0270** [elrumordelaluz/csshake#16]
Not really an issue, more of a request. Is it possible to shake a child element on parent hover for example.

```html
<div class="shake-controller">
   <div class="shake shake-slow"><span class="fa fa-heart"></span></div>
   <h3>I am a title</h3>
</div>
```

this way as I hover over any where within shake-controller my heart icon would shake by the text would stay steady?

**Comment by elrumordelaluz** [comment]
Added this feature in the [last release](https://github.com/elrumordelaluz/csshake/releases/tag/v1.5)
