### ISSUE TITLE
$opacity is not in the documentation and not in the comment for do-shake()

### ISSUE THREAD

**Issue by williamli** [elrumordelaluz/csshake#27]
in _tool.scss opacity is missing from the comments
it is also missing in the readme

/// Do The Shake
/// @param {String}  $name ['shake']              - Name for the keyframes animation
/// @param {Number}  $h [5px]                     - Max number for random to assign in x axis
/// @param {Number}  $v [5px]                     - Max number for random to assign in y axis
/// @param {Number}  $r [3deg]                    - Max number for random rotation
/// @param {Number}  $dur [100ms]                 - animation-duration; valid time value
/// @param {Number}  $precision [.1]              - Precision of the keyframes animation (i.e 2 > 2%, 4%, 6%...)
/// @param {String}  $q [infinite]                - animation-iteration-count; valid value
/// @param {String}  $t [infinite]                - animation-timing-function; valid value
/// @param {Number}  $delay [null]                - animation-delay; valid time value
/// @param {Number}  $chunk [100%]                - Part of 100% where apply the animation
@mixin do-shake(
  $name: 'shake', 
  $h: 5px, 
  $v: 5px, 
  $r: 3deg, 
  $dur: 100ms, 
  $precision: .02, 
  $opacity: false, 
  $q: infinite, 
  $t: ease-in-out, 
  $delay: null,
  $chunk: 100%
  ) {

**Comment by williamli** [comment]
ok. it was in the docs, just not in the _tools.scss comments

**Comment by elrumordelaluz** [comment]
Thanks @williamli. There is the comment [here] (https://github.com/elrumordelaluz/csshake/blob/master/scss/_tools.scss#L25) in the `_tools.scss` file. Maybe you downloaded/forked before a commit with this specific change.
Anyway I found that the `$opacity` explanation is missed in `README.md` file, after the code example. Thanks again!

**Comment by williamli** [comment]
I think I got it from the latest release branch instead of master.
