### ISSUE TITLE
Laggy Animation

### ISSUE THREAD

**Issue by furier** [elrumordelaluz/csshake#28]
Hi, I have tried using this cool css lib on my asp.net MVC5 web page.

The animations does not seem smooth, as in very laggy so it doesnt have a "shake" effect at all it just seem odd, but on your example page it works perfect with the same browser.

So I am wondering what might be the cause for this laggy animation (not smooth) ?

**Comment by elrumordelaluz** [comment]
Hi @furier ,
Could you make a [pen](http://codepen.io/) or show code in some way?

**Comment by furier** [comment]
I have only had this problem on my setup with asp.net mvc5 on windows server 2008 R2 virtual machine with remote desktop. I changed to using anijs instead, and using the rubberband animation instead, so now im unable to make a video to show you.

**Comment by elrumordelaluz** [comment]
ok @furier feel free to comment to reopen this Issue in case you need.
