### ISSUE TITLE
How to get a combination of slow and horizontal?

### ISSUE THREAD

**Issue by kramer65** [elrumordelaluz/csshake#29]
I'm trying to mimic the wide, slow and horizontal shake behaviour of the error bars at Stackoverflow (try not inputting a title and hitting "Post Your Question"). I've tried combining `shake-slow` and `shake-horizontal`, but that seems to have the same result as only using `shake-horizontal`; the animation is still very quick. 

Furthermore, the shake seems to be very small, meaning, it doesn't move much from it's position. Is there a way to make the shake move further from it's initial position so that I can for example have it shake 200 pixels from it's position?

All tips are welcome!

**Comment by elrumordelaluz** [comment]
Hi @kramer65, in this case you need to create your own _CSShake_ animation, and for its purpose you have the `do-shake` mixin. After you clone the repo `git clone https://github.com/elrumordelaluz/csshake.git`, install the basic packages `npm install` (you need [npm installed](https://docs.npmjs.com/cli/install) on your system) and you could start trying what you want with the Sass stuff. 
Try something like 
   ```scss
.shake-horizontal-chunk { 
  @include do-shake('shake-horizontal-chunk', 30, 0, 0, 4s, $chunk: 40%); 
}
   ```
in the `csshake.scss` file and then run `npm run build:raw` or `npm run build:min`.
Keep in mind that the whole code generated in _CSShake_ is based on `random` generated numbers between the values you use in the `mixin`. For a detailed exmplanation of the mixin, read more [here](https://github.com/elrumordelaluz/csshake#customize)

**Comment by kramer65** [comment]
great, thanks!
