### ISSUE TITLE
.freeze doesn't work

### ISSUE THREAD

**Issue by et** [elrumordelaluz/csshake#3]
Since it's misspelled.
See: https://github.com/elrumordelaluz/csshake/blob/master/sass/_shake.scss#L28

**Comment by moneytree-doug** [comment]
The documentation says ``freeze`` is this a mistake in the documentation or the library?

**Comment by elrumordelaluz** [comment]
I think there's a mistake in de docs because the right class is `.freez`. Where did you found it?
