### ISSUE TITLE
Add dedicated CSS style for the default "shake" class

### ISSUE THREAD

**Issue by paya-cz** [elrumordelaluz/csshake#33]
`shake-little`, `shake-slow` and others have dedicated CSS files for very light-weight integration into existing projects (in the `dist` directory). However, no dedicated CSS file is present for the `shake` class. It is available only in the 21kb file which contains all the classes. I suggest adding a new file `csshake-default.css` and `csshake-default.min.css` to cover the `shake` class if someone is not interested in the other shake variants.

**Comment by paya-cz** [comment]
Suggested "csshake-default.css" file content:

    /* * * * * * * * * * * * * * * * * * * * *\  
      CSShake :: shake
      v1.5.0
      CSS classes to move your DOM
      (c) 2015 @elrumordelaluz
      http://elrumordelaluz.github.io/csshake/
      Licensed under MIT
    \* * * * * * * * * * * * * * * * * * * * */
    .shake {
      display: inline-block;
      transform-origin: center center; }

    .shake-freeze,
    .shake-constant.shake-constant--hover:hover,
    .shake-trigger:hover .shake-constant.shake-constant--hover {
      animation-play-state: paused; }

    .shake-freeze:hover,
    .shake-trigger:hover .shake-freeze, .shake:hover,
    .shake-trigger:hover .shake {
      animation-play-state: running; }

    @keyframes shake {
      2% {
        transform: translate(1.5px, 2.5px) rotate(-0.5deg); }
      4% {
        transform: translate(1.5px, -1.5px) rotate(0.5deg); }
      6% {
        transform: translate(1.5px, -1.5px) rotate(-0.5deg); }
      8% {
        transform: translate(0.5px, 2.5px) rotate(0.5deg); }
      10% {
        transform: translate(-0.5px, -0.5px) rotate(1.5deg); }
      12% {
        transform: translate(-0.5px, -0.5px) rotate(-0.5deg); }
      14% {
        transform: translate(2.5px, 0.5px) rotate(-0.5deg); }
      16% {
        transform: translate(-1.5px, 1.5px) rotate(0.5deg); }
      18% {
        transform: translate(2.5px, 0.5px) rotate(-0.5deg); }
      20% {
        transform: translate(-1.5px, 0.5px) rotate(-0.5deg); }
      22% {
        transform: translate(2.5px, -1.5px) rotate(-0.5deg); }
      24% {
        transform: translate(1.5px, 2.5px) rotate(1.5deg); }
      26% {
        transform: translate(-1.5px, -0.5px) rotate(0.5deg); }
      28% {
        transform: translate(1.5px, 1.5px) rotate(-0.5deg); }
      30% {
        transform: translate(2.5px, -1.5px) rotate(-0.5deg); }
      32% {
        transform: translate(0.5px, 2.5px) rotate(-0.5deg); }
      34% {
        transform: translate(-0.5px, 1.5px) rotate(1.5deg); }
      36% {
        transform: translate(0.5px, 1.5px) rotate(1.5deg); }
      38% {
        transform: translate(1.5px, 1.5px) rotate(0.5deg); }
      40% {
        transform: translate(-0.5px, 1.5px) rotate(0.5deg); }
      42% {
        transform: translate(-0.5px, 0.5px) rotate(1.5deg); }
      44% {
        transform: translate(-1.5px, -1.5px) rotate(1.5deg); }
      46% {
        transform: translate(0.5px, -0.5px) rotate(0.5deg); }
      48% {
        transform: translate(-0.5px, 1.5px) rotate(-0.5deg); }
      50% {
        transform: translate(2.5px, -0.5px) rotate(-0.5deg); }
      52% {
        transform: translate(0.5px, -1.5px) rotate(0.5deg); }
      54% {
        transform: translate(2.5px, -1.5px) rotate(0.5deg); }
      56% {
        transform: translate(-1.5px, -0.5px) rotate(0.5deg); }
      58% {
        transform: translate(-1.5px, 2.5px) rotate(1.5deg); }
      60% {
        transform: translate(0.5px, -1.5px) rotate(0.5deg); }
      62% {
        transform: translate(-0.5px, 2.5px) rotate(1.5deg); }
      64% {
        transform: translate(0.5px, 0.5px) rotate(-0.5deg); }
      66% {
        transform: translate(1.5px, -0.5px) rotate(1.5deg); }
      68% {
        transform: translate(-1.5px, -0.5px) rotate(0.5deg); }
      70% {
        transform: translate(-0.5px, 2.5px) rotate(1.5deg); }
      72% {
        transform: translate(1.5px, 0.5px) rotate(0.5deg); }
      74% {
        transform: translate(0.5px, -1.5px) rotate(0.5deg); }
      76% {
        transform: translate(1.5px, 1.5px) rotate(-0.5deg); }
      78% {
        transform: translate(2.5px, -1.5px) rotate(0.5deg); }
      80% {
        transform: translate(-1.5px, 1.5px) rotate(0.5deg); }
      82% {
        transform: translate(-0.5px, 2.5px) rotate(1.5deg); }
      84% {
        transform: translate(1.5px, 1.5px) rotate(-0.5deg); }
      86% {
        transform: translate(2.5px, 0.5px) rotate(1.5deg); }
      88% {
        transform: translate(-0.5px, -1.5px) rotate(-0.5deg); }
      90% {
        transform: translate(1.5px, -0.5px) rotate(-0.5deg); }
      92% {
        transform: translate(0.5px, -1.5px) rotate(1.5deg); }
      94% {
        transform: translate(-0.5px, -0.5px) rotate(0.5deg); }
      96% {
        transform: translate(-0.5px, -1.5px) rotate(-0.5deg); }
      98% {
        transform: translate(-0.5px, -1.5px) rotate(1.5deg); }
      0%, 100% {
        transform: translate(0, 0) rotate(0); } }

    .shake:hover,
    .shake-trigger:hover .shake,
    .shake.shake-freeze,
    .shake.shake-constant {
      animation: shake 100ms ease-in-out infinite; }

**Comment by elrumordelaluz** [comment]
@paya-cz thanks for the idea, included [here](https://github.com/elrumordelaluz/csshake/commit/1d111730e0665bddcca42b8cad2c8bd04974527d)
