### ISSUE TITLE
[request] new release (npm)

### ISSUE THREAD

**Issue by greaterweb** [elrumordelaluz/csshake#36]
In `1.5.0` the `apply-random` function is defined [within the `do-shake` mixin](https://github.com/elrumordelaluz/csshake/blob/v1.5/scss/_tools.scss#L47-L49). In master you have it [defined outside of the `do-shake` mixin](https://github.com/elrumordelaluz/csshake/blob/master/scss/_tools.scss#L14-L16). Chances are the change in master is to address Sass compilers barking _Functions may not be defined within control directives or other mixins_. 

Is it possible to make a new release with the patch that is contained in master?

Thanks!

**Comment by elrumordelaluz** [comment]
@greaterweb thanks for the catch, [this](https://github.com/elrumordelaluz/csshake/blob/v1.5.1/scss/_tools.scss#L14-L16) should be correct now!

Let me know and thanks again.

**Comment by greaterweb** [comment]
Confirmed working. Thanks for the prompt attention, @elrumordelaluz!
