### ISSUE TITLE
Version and link in minified css

### ISSUE THREAD

**Issue by ariunbayar** [elrumordelaluz/csshake#37]
Can you add some description about css in minified file?
For example jquery includes `/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */`
Would be nice to have some link back if `csshake.min.css` is packed with a project files.

Thanks, Love your work! thumbs up

**Comment by elrumordelaluz** [comment]
@ariunbayar Thanks for the idea. Solved [here](https://github.com/elrumordelaluz/csshake/commit/d73157e1e4d0e677968bfcc28c0839f063f4b75a).
