### ISSUE TITLE
shake effect on menu

### ISSUE THREAD

**Issue by madruga88** [elrumordelaluz/csshake#39]
Hello,

could i make this effect showed in this video https://vimeo.com/208065323

using cshake ?

thanks !

**Comment by elrumordelaluz** [comment]
Hello @madruga88 and thanks for the interest.
**CSShake** is based on `random` numbers for its _presets_. You could play around with some numbers in the [reshake](https://github.com/elrumordelaluz/reshake) playground [here](https://elrumordelaluz.github.io/reshake/) but I think you could use the awesome [Bounce.js](http://bouncejs.com/) library to create this kind of _controlled_ animations.
