### ISSUE TITLE
package.json not pointing right to main files

### ISSUE THREAD

**Issue by antivitla** [elrumordelaluz/csshake#40]
Please update your package.json properties to point to your directories and main files. Automatic bundlers like webpack and such cannot find your "module", so we need to copy it to project files to get collected by webpack properly. Probably your initial target audience was bower-users, but npm-guys also deserve your blessed lib :)

Асtually it seemes i don't know good solution to point to style files in package.json (maybe there is still no good one), maybe use antoher fields.. maybe investigate how bootstrap do it (they obviously had to invent something to point all possible bundlers to it's stylesheets in the first place)

**Comment by elrumordelaluz** [comment]
@antivitla I understand what you mean.

>Probably your initial target audience was bower-users 
Not sure if `bower` users but probably most without bundler process -like projects. 

Could you please provide an example on what `webpack`  do or miss about this package? 
_Bootstrap_ has the `js` files as `main`. 

I think a good solution could be `"main": "dist/csshake.css"`, in case this work for you (and hopefully for all the `npm` users) absolutely appreciate a PR!

Thanks for the catch!

**Comment by antivitla** [comment]
Yes, it turns out that `"main": "dist/csshake.css"` makes webpack satisfied. And we can use same syntax for importing it in css|stylus|sass, i've checked it, seems ok.

**Comment by elrumordelaluz** [comment]
Thanks @antivitla !
