### ISSUE TITLE
Shake effect on hover in safari browser

### ISSUE THREAD

**Issue by graphi-x** [elrumordelaluz/csshake#43]
we got a problem with shake only on hover in safari browsers, the same problem i found on your page on section "variation". The first example "Freezed after Shake" doesnt work in safari 11.0.1. On our Website, it has more objects with this effect, only the first one shake. 
we hope u can fix it.

**Comment by trych** [comment]
I have the same issue, only with an additional problem:

When I try to use "Freezed after Shake" in Safari 11.1.2, it does not work. Additionally via some JavaScript, I am changing the `innerHTML` of the shaking div every few seconds, but it somehow "freezes" the bottom part of the text, so only the top part changes (see screenshot).

<img width="530" alt="20180827-154930_screenshot_safari" src="https://user-images.githubusercontent.com/9803905/44663579-44c92900-aa11-11e8-854b-8214eb8c2e97.png">

Any way of doing something about this?

**Comment by elrumordelaluz** [comment]
Seems solved on _Safari_ `v 12.1.1`. Feel free to re-open or open a new _Issue_ in any case.
